# Generated by Django 2.0 on 2020-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('edition', models.CharField(max_length=10)),
                ('foil', models.BooleanField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
