# Generated by Django 2.0 on 2020-04-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
