# Generated by Django 2.0 on 2020-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcard',
            name='bag',
            field=models.ManyToManyField(blank=True, to='Inventory.Bag'),
        ),
    ]
