# Generated by Django 2.0 on 2020-07-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20200419_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
