# Generated by Django 2.0 on 2020-07-26 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_card_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('edition', models.CharField(max_length=10)),
                ('foil', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='profit',
        ),
    ]
