# Generated by Django 2.0 on 2020-08-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20200726_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('cards_quantity', models.IntegerField()),
                ('card_evaluation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
