# Generated by Django 2.0 on 2020-08-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_marketevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('bag_id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False)),
                ('id', models.CharField(editable=False, max_length=100)),
                ('bag_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='card',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sold',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
