# Generated by Django 2.0 on 2020-08-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_auto_20200805_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='foil',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='name',
        ),
    ]
