# Generated by Django 2.0 on 2020-08-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_auto_20200805_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
