# Generated by Django 2.0 on 2020-08-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_bag_quantity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bag',
            index=models.Index(fields=['id'], name='Inventory_b_id_c65176_idx'),
        ),
    ]
