# Generated by Django 2.0 on 2020-08-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20200807_0033'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bag',
            name='Inventory_b_id_c65176_idx',
        ),
        migrations.AlterField(
            model_name='bag',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Card'),
        ),
        migrations.AddIndex(
            model_name='bag',
            index=models.Index(fields=['id'], name='Inventory_b_id_id_f8ec75_idx'),
        ),
    ]
