# Generated by Django 2.0 on 2020-08-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20200807_2031'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bag',
            name='Inventory_b_id_id_f8ec75_idx',
        ),
        migrations.RenameField(
            model_name='bag',
            old_name='id',
            new_name='card',
        ),
        migrations.AddIndex(
            model_name='bag',
            index=models.Index(fields=['card'], name='Inventory_b_card_id_9a88df_idx'),
        ),
    ]
